repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      # - id: terraform_tfsec
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true

        # args: ["--output-file", "README.md", "./envs/dev/network"]
        # args:
        #   [
        #     "markdown",
        #     "table",
        #     "./envs/dev/network",
        #     "--output-file",
        #     "README.md",
        #   ]
